import Navigation from "@/features/navigation/Navigation"
import { decrement, increment } from "@/features/productList/productSlice"
import Head from 'next/head'
import Image from "next/image"
import { useState, useEffect } from "react"
import { useSelector, useDispatch } from 'react-redux'

export default function Cart({  }) {
  <Head>
    <title>Cart</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  const cart = useSelector((state) => state.product.products)
  const dispatch = useDispatch()
  console.log('cart', cart);
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)
  
  useEffect(() => {
    setLoading(true)
    cart.map(item => {
      fetch(`https://fakestoreapi.com/products/${item.productId}`)
        .then((res) => res.json())
        .then((newData) => {
          setData((oldState) => {
            if (oldState) {
              return [...oldState, {
                ...newData,
                quantity: item.quantity
              }]
            } else if (newData) {
              return [{
                ...newData,
                quantity: item.quantity
              }]
            }
          })
          setLoading(false);
        }).catch(function(error) {
          console.log(error);
          setLoading(false);
        });
    });
  }, []);

  
  function isCherries(productObj) {
    return productObj.productId === 1;
  }
  
  

  // if (isLoading) return <p>Loading...</p>
  // if (!data) return <p>No profile data</p>

  // Render data...
  return (
    <div className="mt-4">
      <Navigation />
      {isLoading && <p>Loading...</p>}
      {!data && !isLoading && <p>No items</p>}
      
      {
        data && data.map(item => {
          return <div key={item.id} className="mt-8">
            <Image 
              src={item.image}
              width={100}
              height={100}
              alt={item.title}
            />
            <div>{item.title}</div>
            <div>
              <button 
                className="bg-red-500 rounded-md w-5 h-5 text-white inline-flex items-center justify-center"
                onClick={() => dispatch(decrement(item.id))}
              >-</button> 
              Quantity: {cart.find(({productId}) => productId === item.id)?.quantity}
              <button className="bg-red-500 rounded-md w-5 h-5 text-white inline-flex items-center justify-center" 
              onClick={() => dispatch(increment(item.id))}>+</button>
            </div>

          </div>
        })
      }
    </div>
  )

}

