import Head from 'next/head'
import ProductList from '@/features/productList/ProductList';

export default function Home({products}) {
  return (
    <>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductList products={products}/>
    </>
  )
}


/* getStaticProps */
export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('https://fakestoreapi.com/products')
  const products = await res.json()

  // By returning { props: { products } }, the Blog component
  // will receive `products` as a prop at build time
  return {
    props: {
      products,
    },
  }
}